CREATE TABLE `d_paciente` (
  `id_paciente` int(10) NOT NULL,
  `nombre_p` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `fec_nac` date DEFAULT NULL,
  `edad_p` varchar(10) NOT NULL,
  `sexo_p` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `domicilio_p` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `cp_p` varchar(5) NOT NULL,
  `tel_p` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `cel_pac` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `correo` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `ocupacion_p` varchar(50) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  `fecha_ing` date DEFAULT NULL,
  `nombre_f` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `tel_f` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `cel_f` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `paren_f` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `imagen` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo1` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo2` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo3` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo4` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo5` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo6` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo7` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo8` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo9` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo10` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo11` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo12` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo13` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo14` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo15` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo16` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo17` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo18` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo19` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo20` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo21` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo22` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo23` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo24` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo25` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo26` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `campo27` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'pagado',
  `campo28` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'tipo_boleto_uni',
  `campo29` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'matricula-venta-linea',
  `campo30` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'carrera-venta-linea',
  `nota_p` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `id_medico` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `id_doctor` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `rfc` varchar(13) NOT NULL,
  `form_pago` int(10) NOT NULL,
  `persona` varchar(10) NOT NULL,
  `razon_social` varchar(200) NOT NULL,
  `elaborado` varchar(100) NOT NULL,
  `dias_cred` int(10) NOT NULL,
  `user` varchar(25) NOT NULL,
  `pass` varchar(255) NOT NULL,
  `autorizado` varchar(2) NOT NULL,
  `ultimo_acceso` datetime DEFAULT NULL,
  `creado` varchar(2) NOT NULL,
  `calificaciones` char(3) NOT NULL,
  `precio` varchar(10) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `reg_fisc_rec` int(5) NOT NULL,
  `dom_fisc_rec` int(10) NOT NULL,
  `codigo` varchar(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;